package com.chhorvorn.material

val item = mutableListOf(
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
    TASK_ITEM(uid = 0, "Microsoft", "View new tips", status = true),
)